server:
  servlet:
    context-path: /api

spring:
  application:
    name: SKoro
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true

