spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/skoro_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    format_sql: true