spring:
  profiles:
    active: local
  datasource:
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: 3600000
  refresh-token-validity-ms: 1209600000